<?php
/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) :?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()) :?>
        <div class="field qty">
            <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
            <div class="control" data-bind="scope: 'change_qty'">
                <button type="button" class="qty-minus" data-bind="click: decreaseQty">-</button>
                <input type="number"
                       name="qty"
                       id="qty"
                       min="1"
                       data-bind="value: qty()"
                       title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                />
                <button type="button" class="qty-plus" data-bind="click: increaseQty">+</button>
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><?= $block->escapeHtml($buttonTitle) ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>

<script type="text/x-magento-init">
{
    "#product_addtocart_form": {
        "Magento_Catalog/js/validate-product": {}
    }
}
</script>
 <!-- INIT Knockout Component -->
<script type="text/x-magento-init">
    {
    "*": {
        "Magento_Ui/js/core/app": {
        "components": {
        "change_qty": {
        "component": "Magento_Catalog/js/product/qty",
        "defaultQty": <?= $block->getProductDefaultQty() * 1 ?>
                    }
                }
            }
        }
    }
</script>